
alg_name: "LoRA"
model_name: "gpt2"
device: 1

lora_type: "lora"
layers: []
num_steps: 5
batch_size: 4
max_length: 30
lr: 5e-3
weight_decay: 0
kl_factor: 0
rank: 8
lora_alpha: 32
lora_dropout: 0.1
norm_constraint: false
target_modules: ["c_attn"] 
model_parallel: false